type: object
properties:
  description:
    type: string
  exports:
    type: object
    additionalProperties:
      type: object
      properties:
        engine:
          type: string
        helper:
          type:
            - string
            - object
          additionalProperties:
            type: string
        processor:
          type: string
        generator:
          type: string
        schema:
          type:
            - object
            - string
        spec:
          type: string
  imports:
    type: object
    additionalProperties:
      type:
        - string
        - object
      properties:
        aliases:
          type: object
          additionalProperties:
            type: string
        version:
          type: string
  name:
    type: string
  release:
    type: string
  version:
    type:
      - number
      - string
